# Generated by Django 4.1.2 on 2022-10-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=100)),
                (
                    "esstimated_duration_minutes",
                    models.IntegerField(default=0, verbose_name="duration"),
                ),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
            ],
        ),
    ]
