# Generated by Django 4.1.3 on 2022-11-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_recipe_ingredients_ingredient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="esstimated_duration_minutes",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="recipe_name",
            new_name="name",
        ),
    ]
